default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: fellowship_dev
  host: localhost
  username: fellowship
  password: a12345

test:
  <<: *default
  database: fellowship_test
  host: localhost
  username: fellowship
  password: a12345

production:
  <<: *default
  database: fellowship_prod
